### ISSUE TITLE
cant run the app

### ISSUE THREAD

**Issue by Avin-Techv** [brijshah/Django-Fileserver#1]
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f1d7f6cf488>
Traceback (most recent call last):
  File "/home/techv/Documents/djangoprojects/file-download/env/lib/python3.5/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/techv/Documents/djangoprojects/file-download/env/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/techv/Documents/djangoprojects/file-download/env/lib/python3.5/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/home/techv/Documents/djangoprojects/file-download/env/lib/python3.5/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/home/techv/Documents/djangoprojects/file-download/env/lib/python3.5/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/techv/Documents/djangoprojects/file-download/env/lib/python3.5/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/techv/Documents/djangoprojects/file-download/env/lib/python3.5/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/techv/Documents/djangoprojects/file-download/env/lib/python3.5/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/techv/Documents/djangoprojects/file-download/env/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/techv/Documents/djangoprojects/file-download/Django-Fileserver/fileserver/models.py", line 9, in <module>
    class File(models.Model):
  File "/home/techv/Documents/djangoprojects/file-download/Django-Fileserver/fileserver/models.py", line 11, in File
    user = models.ForeignKey(User, related_name='files') #file is tied to a user; user can access all files through the column 'files'
TypeError: __init__() missing 1 required positional argument: 'on_delete'

**Comment by shahabaz** [comment]
Do this 
    user = models.ForeignKey(User, related_name='files',on_delete=models.CASCADE) #file is tied to a user; user can access all files through the column 'files'
